In [50]:
from tensorflow.keras.preprocessing.text import one_hot

In [51]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'i am good developer',
        'your videos are good']


In [52]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am good developer',
 'your videos are good']

In [53]:
vocab_size = 10000

In [54]:
onehot_repr = [one_hot(words, vocab_size) for words in sent]
print(onehot_repr)

[[1213, 8395, 2368, 4251], [1213, 8395, 2368, 2250], [1213, 596, 2368, 534], [859, 8527, 4371, 3191], [5230, 294, 2710, 4371]]


In [55]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [56]:
import numpy as np

In [57]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1213 8395 2368 4251]
 [   0    0    0    0 1213 8395 2368 2250]
 [   0    0    0    0 1213  596 2368  534]
 [   0    0    0    0  859 8527 4371 3191]
 [   0    0    0    0 5230  294 2710 4371]]


In [58]:
dim=15

In [59]:
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [60]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 8, 15)             150000    
                                                                 
Total params: 150,000
Trainable params: 150,000
Non-trainable params: 0
_________________________________________________________________


In [62]:
embedded_docs[0]

array([   0,    0,    0,    0, 1213, 8395, 2368, 4251])

In [63]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 24ms/step
[[ 1.8174890e-02 -2.9457582e-02  4.7813240e-02  2.8921191e-02
  -3.3936612e-03  5.8644041e-03 -4.7902353e-03 -1.7818023e-02
  -1.8575776e-02 -1.8810486e-02 -2.3317087e-02 -1.4342129e-02
   8.7252744e-03 -2.1090508e-03 -2.0131409e-02]
 [ 1.8174890e-02 -2.9457582e-02  4.7813240e-02  2.8921191e-02
  -3.3936612e-03  5.8644041e-03 -4.7902353e-03 -1.7818023e-02
  -1.8575776e-02 -1.8810486e-02 -2.3317087e-02 -1.4342129e-02
   8.7252744e-03 -2.1090508e-03 -2.0131409e-02]
 [ 1.8174890e-02 -2.9457582e-02  4.7813240e-02  2.8921191e-02
  -3.3936612e-03  5.8644041e-03 -4.7902353e-03 -1.7818023e-02
  -1.8575776e-02 -1.8810486e-02 -2.3317087e-02 -1.4342129e-02
   8.7252744e-03 -2.1090508e-03 -2.0131409e-02]
 [ 1.8174890e-02 -2.9457582e-02  4.7813240e-02  2.8921191e-02
  -3.3936612e-03  5.8644041e-03 -4.7902353e-03 -1.7818023e-02
  -1.8575776e-02 -1.8810486e-02 -2.3317087e-02 -1.4342129e-02
   8.7252744e-03 -2.1090508e-03 -2.0131409e-02]
 [ 3.0836117